### ISSUE TITLE
ClobberError with conda-forge::zeromq

### ISSUE THREAD

**Issue by dhirschfeld** [AnacondaRecipes/pyzmq-feedstock#2]
I originally opened this issue at https://github.com/conda-forge/zeromq-feedstock/issues/32 but whilst writing it up I think the problem is with the packaging of pyzmq/zeromq on the defaults channels.

I have both `conda-forge` and `defaults` in my channel list and also `channel_priority: false` which means conda is free to mix-and-match channels between zeromq and pyzmq. Unfortunately, because of the differences in packaging this results in a `ClobberError`

```
ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::zeromq-4.2.5-vc14_1, defaults::pyzmq-17.0.0-py36hfa6e2cd_1
  path: 'library/lib/libzmq.lib'
```

It would be good if the packaging of the libraries were aligned such that you could reasonably mix and match between channels.

From the comparison below, it seems to me that `defaults::pyzmq` *shouldn't* be packaging the library file `libzmq.lib`, that instead it should be provided by `zeromq` as it is in the `conda-forge` packages.

Also, in `defaults::zeromq` the `libzmq.lib` file seems to be incorrectly placed in the bin folder rather than under lib.

<br>
<table>
<tr><th colspan="2">

## `pyzmq`
</th></tr>
<tr><th>conda-forge</th><th>defaults</th></tr>
<tr>
<td>

```diff
  pyzmq-17.0.0-py36_4
  │ 
  ├───info
  │   └───recipe
  └───Lib
      └───site-packages
          ├───pyzmq-17.0.0-py3.6.egg-info
          └───zmq
              ├───asyncio
              ├───auth
              │   └───asyncio
              ├───backend
              │   ├───cffi
              │   └───cython
              ├───devices
              ├───eventloop
              │   └───minitornado
              │       └───platform
              ├───green
              │   └───eventloop
              ├───log
              ├───ssh
              ├───sugar
              ├───tests
              │   └───asyncio
              └───utils
```
</td>
<td>

```diff
  pyzmq-17.0.0-py36hfa6e2cd_1
  │ 
  ├───info
  │   ├───recipe
  │   └───test
  ├───Lib
  │   └───site-packages
  │       ├───pyzmq-17.0.0-py3.6.egg-info
  │       └───zmq
  │           ├───asyncio
  │           ├───auth
  │           │   └───asyncio
  │           ├───backend
  │           │   ├───cffi
  │           │   └───cython
  │           ├───devices
  │           ├───eventloop
  │           │   └───minitornado
  │           │       └───platform
  │           ├───green
  │           │   └───eventloop
  │           ├───log
  │           ├───ssh
  │           ├───sugar
  │           ├───tests
  │           │   └───asyncio
  │           └───utils
+ └───Library
+     └───lib
+             libzmq.lib
```
</td>
</tr>
</table>

<hr>

<table>
<tr><th colspan="2">

## `zeromq`
</th></tr>
<tr><th>conda-forge</th><th>defaults</th></tr>
<tr>
<td>

```diff
  zeromq-4.2.5-vc14_1
  │
  ├───info
  │   └───recipe
  └───Library
      ├───bin
      │       libzmq-mt-4_2_5.dll
      │       libzmq.dll
      │
      ├───include
      ├───lib
      │   │   libzmq-mt-4_2_5.lib
      │   │   libzmq-mt-s-4_2_5.lib
+     │   │   libzmq.lib
      │   │
      │   └───pkgconfig
      └───share
          ├───cmake
          │   └───ZeroMQ
          └───zmq
```
</td>
<td>

```diff
  zeromq-4.2.5-hc6251cf_0
  │
  ├───info
  │   ├───recipe
  │   └───test
  └───Library
      ├───bin
      │       libzmq-mt-4_2_5.dll
      │       libzmq.dll
+     │       libzmq.lib
      │
      ├───include
      ├───lib
      │   │   libzmq-mt-4_2_5.lib
      │   │   libzmq-mt-s-4_2_5.lib
      │   │
      │   └───pkgconfig
      └───share
          ├───cmake
          │   └───ZeroMQ
          └───zmq
```
</td>
</tr>
</table>

**Comment by dhirschfeld** [comment]
Wondering if this is in any way related to #1?

**Comment by dhirschfeld** [comment]
Ping @mingwandroid! In case you haven't already seen this (I'm not sure how well monitored this repo is)

**Comment by dhirschfeld** [comment]
ping @msarahan! Not sure who might be interested in fixing this but I thought I'd ping you since you're listed in the recipe and I'm still unsure if anyone has seen this.

I think it's a fairly important bug as it can result in segfaults.

**Comment by jjhelmus** [comment]
Removing `libzmq.lib` from the `pyzmq` package and installing it in the Library/lib directory in the `zeromq` package is reasonable.  I think this change should wait for a new release of `zeromq`.  Having `zeromq` packages which differ only in build number with different `libzmq.lib` location will cause ClobberErrors if an incompatible build of `pyzmq` is selected.

**Comment by dhirschfeld** [comment]
***xref:*** https://github.com/AnacondaRecipes/zeromq-feedstock/issues/4

**Comment by dhirschfeld** [comment]
@jjhelmus - `defaults::zeromq` is two versions behind the latest so it might be a good time to schedule these changes since the version discrepancy is now causing DLL load errors which are breaking conda - https://github.com/conda/conda/issues/8171

The breakage is probably the fault of `nb_conda_kernels` which should probably be more defensive in it's `post-link.bat` script but the end result is that conda breaks (for this somewhat particular usecase)

**Comment by dhirschfeld** [comment]
***Update:***
The breakage ***is*** the fault of `nb_conda_kernels` - https://github.com/AnacondaRecipes/nb_conda_kernels-feedstock/issues/1

<br>
It's still probably a good idea to fix the `pyzmq`/`zeromq` packaging though...

**Comment by dhirschfeld** [comment]
As @jjhelmus mentioned on [gitter](https://gitter.im/conda-forge/conda-forge.github.io?at=5e68098e145f4d695632b395) this is now fixed in the latest packages.

Tested with:
```
zeromq =4.3.1
pyzmq =18.1.1
```
